# Generated by Django 3.0.3 on 2020-02-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=264)),
                ('state', models.CharField(max_length=264)),
                ('station', models.CharField(max_length=264)),
                ('last_update', models.DateTimeField()),
                ('city_id', models.IntegerField()),
                ('pollutant_id', models.CharField(max_length=264)),
                ('pollutant_max', models.IntegerField()),
                ('pollutant_min', models.IntegerField()),
                ('pollutant_unit', models.CharField(max_length=264)),
            ],
        ),
    ]
